services:
  member-db:
    image: mysql:8.0
    container_name: member-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: memberdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "4306:3306"

  auth-db:
    image: mysql:8.0
    container_name: auth-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: authdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "4399:3306"
      
  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  db_data:
  redis_data:
