server:
  port: 10000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-service
              uri: lb://member-service
              predicates:
                - Path=/member-service/**
              filters:
                - RewritePath=/member-service/(?<segment>.*), /api/members/${segment}
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth-service/**
              filters:
                - RewritePath=/auth-service/(?<segment>.*), /api/auth/${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentEnvironmentOnly}
