spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:18888"

logging:
  level:
    root: INFO
    com.msa.auth: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
